# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


# default rules
homepage:
  url:   /
  param: { module: list, action: index }

list_permalink:
  url:     /:slug
  class:   sfDoctrineRoute
  options:      { model: SkinnyList, type: object, method: getObjectBySlug }
  param:        { module: list, action: show }
  requirements: { sf_method: get }

# generic rules
# please, remove them by adding more specific rules
default:
  url:   /:module/:action/*

