homepage:
  url:   /
  param: { module: list, action: index }

list_permalink:
  url:     /:slug
  class:   sfDoctrineRoute
  options:      { model: SkinnyList, type: object, method: getObjectBySlug }
  param:        { module: list, action: show }
  requirements: { sf_method: get }

list:
  class: sfDoctrineRouteCollection
  options: 
    model:                SkinnyList
    module:               list
    prefix_path:          list
    with_wildcard_routes: true

sorted_list:
  url:     /list/sort
  param:   { module: list, action: sort }
