homepage:
  url:   /
  param: { module: list, action: index }

list_permalink:
  url:     /:slug
  class:   sfDoctrineRoute
  options:      { model: SkinnyList, type: object, method: getObjectBySlug }
  param:        { module: list, action: show }
  requirements: { sf_method: get }

sorted_list:
  url:     /list/sort
  param:   { module: list, action: sort }

new_list:
  url:     /list/new
  param:   { module: list, action: new }

edit_list:
  url:     /list/edit/:id
  param:   { module: list, action: update }

delete_list:
  url:     /list/delete/:id
  param:   { module: list, action: delete }

add_item:
  url:     /list/addItem/*
  param:   { module: list, action: addSkinnyItem }

update_item:
  url:     /list/updateItem/*
  param:   { module: list, action: updateSkinnyItem }

delete_item:
  url:     /list/deleteItem/*
  param:   { module: list, action: deleteSkinnyItem }

print:
  url:     /list/print/*
  param:   { module: list, action: print }

checkItem:
  url:     /list/checkItem/*
  param:   { module: list, action: checkItem }

uncheckItem:
  url:     /list/uncheckItem/*
  param:   { module: list, action: uncheckItem }

register: 
  url:     /user/register
  param:   { module: sfGuardAuth, action: register }

activate:
  url:     /user/activate/token/:token
  param:   { module: sfGuardAuth, action: activate }

changePassword: 
  url:     /user/changePassword
  param:   { module: sfGuardAuth, action: changePassword }

rememberPassword:
  url:     /user/rememberPassword
  param:   { module: sfGuardAuth, action: password }

my_lists:
  url:     /list/my-lists
  param:   { module: list, action: mylists }
