# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - main.css
    - jquery.markedit.css    
    - 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/flick/jquery-ui.css'

  javascripts:    
    - 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'
    - 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js'
    - jquery.markedit.js
    - showdown.js

  has_layout:     true
  layout:         layout
