edit:
  is_secure: on
  credentials: [[owner]]
addSkinnyItem:
  is_secure: on
  credentials: [[owner]]
updateSkinnyItem:
  is_secure: on
  credentials: [[owner]]
sort:
  is_secure: off
deleteSkinnyItem:
  is_secure: on
  credentials: [[owner]]
mylists:
  is_secure: on
update:
  is_secure: on
  credentials: [[owner]]
delete:
  is_secure: on
  credentials: [[owner]]
