edit:
  is_secure: on
  credentials: [[owner]]
addSkinnyItem:
  is_secure: on
  credentials: [[owner]]
updateSkinnyItem:
  is_secure: on
  credentials: [[owner]]
deleteSkinnyItem:
  is_secure: on
  credentials: [[owner]]
mylists:
  is_secure: on
