edit:
  is_secure: on
  credentials: [[admistrator owner]]
sort:
  is_secure: on
  credentials: [[admistrator owner]]
addSkinnyItem:
  is_secure: on
  credentials: [[admistrator owner]]
updateSkinnyItem:
  is_secure: on
  credentials: [[admistrator owner]]
deleteSkinnyItem:
  is_secure: on
  credentials: [[admistrator owner]]
